version: "3.8"

services:
  backend_app:
    image: habit-tracker:latest
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - db_migrations

  db_migrations:
    image: habit-tracker:latest
    build: .
    env_file:
      - .env
    command: [ "poetry", "run", "python", "manage.py", "migrate" ]
    volumes:
      - ./:/app
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  # frontend_app:
  #   image: team-challenge:latest
  #   build:
  #     context: ../team-challenge/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ../team-challenge/src:/app/src

volumes:
  data: