# Generated by Django 4.2.4 on 2023-08-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "camera feature",
                "verbose_name_plural": "camera features",
                "db_table": "camera_features",
            },
        ),
        migrations.CreateModel(
            name="CommunicationStandarts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "communication standart",
                "verbose_name_plural": "communication standarts",
                "db_table": "communication_standarts",
            },
        ),
        migrations.CreateModel(
            name="Smartphone",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="smartphone",
                        serialize=False,
                        to="products.product",
                    ),
                ),
                (
                    "screen_size",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="screen size"
                    ),
                ),
                (
                    "screen_type",
                    models.CharField(max_length=255, verbose_name="screen type"),
                ),
                (
                    "screen_resolution",
                    models.CharField(max_length=255, verbose_name="screen resolution"),
                ),
                (
                    "screen_refresh_rate",
                    models.CharField(
                        max_length=255, verbose_name="screen refresh rate"
                    ),
                ),
                (
                    "screen_material",
                    models.CharField(max_length=255, verbose_name="screen material"),
                ),
                (
                    "sim_card_number",
                    models.PositiveIntegerField(verbose_name="number of sim cards"),
                ),
                (
                    "sim_card_size",
                    models.CharField(max_length=255, verbose_name="size of sim card"),
                ),
                (
                    "is_e_sim_supported",
                    models.BooleanField(verbose_name="E-Sim support"),
                ),
                (
                    "operating_system",
                    models.CharField(max_length=255, verbose_name="operating system"),
                ),
                ("processor", models.CharField(max_length=255)),
                ("number_of_cores", models.PositiveIntegerField()),
                ("internal_memory", models.CharField(max_length=255)),
                ("ram", models.CharField(max_length=255)),
                (
                    "main_camera",
                    models.CharField(max_length=255, verbose_name="main camera"),
                ),
                (
                    "number_of_main_cameras",
                    models.PositiveIntegerField(verbose_name="number of main cameras"),
                ),
                (
                    "front_camera",
                    models.CharField(max_length=255, verbose_name="front camera"),
                ),
                (
                    "front_camera_placement",
                    models.CharField(
                        max_length=255, verbose_name="front camera placement"
                    ),
                ),
                ("is_flash_available", models.BooleanField()),
                (
                    "battery_life_in_hours",
                    models.PositiveIntegerField(verbose_name="battery life in hours"),
                ),
                (
                    "is_fast_charging_available",
                    models.BooleanField(verbose_name="fast charging"),
                ),
                (
                    "is_wireless_charging_available",
                    models.BooleanField(verbose_name="wireless charging"),
                ),
                (
                    "communication_standarts",
                    models.ManyToManyField(
                        related_name="smartphones",
                        to="smartphones.communicationstandarts",
                        verbose_name="communication standarts",
                    ),
                ),
                (
                    "front_camera_features",
                    models.ManyToManyField(
                        related_name="smartphones_with_front_camera_feature",
                        to="smartphones.camerafeatures",
                        verbose_name="front camera features",
                    ),
                ),
                (
                    "main_camera_features",
                    models.ManyToManyField(
                        related_name="smartphones_with_main_camera_feature",
                        to="smartphones.camerafeatures",
                        verbose_name="main camera features",
                    ),
                ),
            ],
            options={
                "verbose_name": "smartphone",
                "verbose_name_plural": "smartphones",
                "db_table": "smartphones",
            },
            bases=("products.product",),
        ),
    ]
