# Generated by Django 4.2.4 on 2023-08-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Smartphone",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                ("attribute_titles", models.JSONField()),
                ("attribute_labels", models.JSONField()),
                ("screen_size", models.DecimalField(decimal_places=2, max_digits=5)),
                ("screen_type", models.CharField(max_length=255)),
                ("screen_resolution", models.CharField(max_length=255)),
                ("screen_refresh_rate", models.CharField(max_length=255)),
                ("sim_card_number", models.PositiveIntegerField()),
                ("sim_card_size", models.CharField(max_length=255)),
                ("is_e_sim_supported", models.BooleanField()),
                ("operating_system", models.CharField(max_length=255)),
                ("processor", models.CharField(max_length=255)),
                ("number_of_cores", models.PositiveIntegerField()),
                ("memory", models.CharField(max_length=255)),
                ("main_camera", models.CharField(max_length=255)),
                ("front_camera", models.CharField(max_length=255)),
                ("is_flash_available", models.CharField(max_length=255)),
                ("video_resolution", models.CharField(max_length=255)),
                ("battery_life", models.CharField(max_length=255)),
            ],
        ),
    ]
